spring:
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        show_sql: true
    database: postgresql
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: stavssj15394
